GET http://localhost:8080/students/all

###
POST http://localhost:8080/students/add
Accept: application/json
Content-Type: application/json
 {
    "name":"abhishek",
    "email":"abc@gmail.com",
    "rollnumber":22,
    "gender":"Male",
    "age":22
 }